profile:
  name: Customer Profile Dev
  description: This is a dev profile
server:
  port: 0 # Para que eureka asigne puerto automaticamente
  error:
    include-stacktrace: never
  servlet:
    contextPath: "/api/customer-microservice"
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
    username: postgres
    password: 123
  data:
    rest:
      base-path: "${serverconfig.api-base-path}"
      detection-strategy: "annotated"
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 215MB
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
  instance:
    instanceId: ${spring.application.name}:${random.uuid}
    preferIpAddress: true
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

test:
  testProp: Property of test