profile:
  name: Customer Profile Dev
  description: This is a dev profile
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booking
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"